# Generated by Django 4.2.6 on 2023-11-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_remove_sensordata_hum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.CharField(max_length=10)),
                ('temperature', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
