# Generated by Django 4.2.6 on 2023-12-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_remove_data_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.CharField(default='--', max_length=30, null=True),
        ),
    ]
